name: Find Some More github Repositories With Actions

on:
  schedule:
    - cron: '42 * * * *'
  push:

jobs:
  find-more:
    name: Find More
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile
        run: ant actionscrossref.xml
